name: Windows Debug (tmate)

on:
  push:
    branches:
      - win

  workflow_dispatch:

jobs:
  debug:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
